# Generated by Django 4.1.7 on 2023-03-27 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_rename_tasklist_taskview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskView",
            new_name="Task",
        ),
    ]
